### ISSUE TITLE
404 Not Found: Is modrewrite configured on your system?

### ISSUE THREAD

**Issue by ricard0g0mes** [inverse/hassio-addon-emoncms#12]
404 Not Found: Is modrewrite configured on your system?

Error when trying to register the first user.

Config:

databases:
  - homeassistant
logins:
  - username: homeassistant
    password: xxxxxx
rights:
  - username: homeassistant
    database: homeassistant

**Comment by inverse** [comment]
Hi @ricard0g0mes!

What version of the extension are you installing? I just did a fresh install within the devcontainers setup included in this from the tagged `0.1.0`. 

modrewrite is not used in this addon since it's based on php-fpm + nginx.

Any other information to help debug this would be useful :)

**Comment by ricard0g0mes** [comment]
Tell me how can I help debugging.
I'm using rp4 with hassos

**Comment by inverse** [comment]
Are you able to provide a screenshot of the error?

**Comment by ricard0g0mes** [comment]
![Screenshot_20210407-064612_Chrome](https://user-images.githubusercontent.com/10976309/113816646-02415e80-976d-11eb-96dd-cd76bccf2d3a.jpg)
Here it is

**Comment by ricard0g0mes** [comment]
![image](https://user-images.githubusercontent.com/10976309/114004391-84f21880-9856-11eb-9ce2-98cf916e1f53.png)
![image](https://user-images.githubusercontent.com/10976309/114004462-976c5200-9856-11eb-937d-468b3bcb46e8.png)

**Comment by inverse** [comment]
Hi @ricard0g0mes sorry for the delay.

The error is coming from here: https://github.com/emoncms/emoncms/blob/813a02a46bbb16c8d7f326687db97add01743f23/Modules/user/user.js#L59

I'm guessing it's because this URL isn't working `http://<hass-host>:9541/user/login` 

I'm still unable to reproduce the error :(

![image](https://user-images.githubusercontent.com/713525/114227811-c4fbed00-9975-11eb-80c4-b8875e19ddf3.png)

It looks fine for me :(

**Comment by ricard0g0mes** [comment]
You can try it if you want.
[https://ricardogomes.duckdns.org:9541](https://ricardogomes.duckdns.org:9541)
Try to register and the error will come.

**Comment by ricard0g0mes** [comment]
disabled ssl and it's working now!
thank you

**Comment by inverse** [comment]
Hey sorry for getting back to me on this - I was trying to investigate last night but didn't far with it. 

I'll add this as a known limitation of something that needs to be worked on as TLS should work.

**Comment by ricard0g0mes** [comment]
![image](https://user-images.githubusercontent.com/10976309/114298826-232ceb00-9ab0-11eb-914f-0d73531805aa.png)
:(

**Comment by inverse** [comment]
Hi @ricard0g0mes found the SSL issue I think.

https://github.com/inverse/hassio-addon-emoncms/pull/14 - It was a copy paste error from the base I used for the extension.

Just [released](https://github.com/inverse/hassio-addon-emoncms/releases/tag/0.1.1) `0.1.1`  which should solve this.

Could you create a new issue for the next issue you're facing - I'm not a emoncms user so you may have to explain more where this is occurring.
