### ISSUE TITLE
addon not downloading in hass.io

### ISSUE THREAD

**Issue by jaim-fads** [inverse/hassio-addon-emoncms#5]
I am new to home assistant and trying to get my arduino code to communicate to HA. I downloaded Maria DB as a prerequisite and followed the documentation for the config file. I was unable to install it from the UI, screenshot attached with the error message.
![Capture](https://user-images.githubusercontent.com/48386905/111095687-383b4c00-84fb-11eb-9805-ebcca3446209.PNG)

When attempting to download emoncms addon from this repo, the cli reports back: Error: addon emoncms with version latest does not exist in the store.

**Comment by inverse** [comment]
Latest version on master has fixed that. I'm new to addon development so thanks for giving the feedback. 

Will try to publish to dockerhub to avoid these issues going forward.

**Comment by roy13** [comment]
![image](https://user-images.githubusercontent.com/13426512/111857716-8b901d00-8987-11eb-8739-1dbe03d1548c.png)
Hi, I also got this one when using GUI to install.

**Comment by inverse** [comment]
Hi @roy13,

Should be fixed now - I just verified myself.


![image](https://user-images.githubusercontent.com/713525/111884822-4e964b80-89c4-11eb-8419-1ead251eb55f.png)


All images are correctly tagged and pushed to dockerhub and the `config.json` now reflects the version correctly (`0.1.0`)


Let me know if this issue is fixed for you and I will close the ticket.

**Comment by inverse** [comment]
@jaim-fads or @roy13 can you confirm this issue is resolved?

**Comment by roy13** [comment]
Sorry I'm really keen to get HASSIO on to a HDD instead of SD before I start but can't seem to work out a reliable way. Also I imagine I can't use emonhub with your setup so I've left it.
However I loaded it this morning to test for you & it installed without any errors!
Thanks 👍

On Mar 25, 2021 10:14 PM, Malachi Soord ***@***.***> wrote:

@jaim-fads<https://github.com/jaim-fads> or @roy13<https://github.com/roy13> can you confirm this issue is resolved?
